wifi:
  ap:
    ssid: '${friendly_name}'
    
# Allow provisioning Wi-Fi via serial
improv_serial:
# Allow provisioning Wi-Fi via BLE
esp32_improv:
  authorizer: none

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
#captive_portal:
