---
# Heom Pulse
#
# Read your electricity meter by means of the pulse LED on your
# meter, useful if you do not have a serial port (P1).
# Original: © Klaas Schoute
# Adaptation: Paul Schulz

substitutions:
  device_name: esphome-pulse
  friendly_name: ESPHome Pulse
  project_version: "0.0.1"
  device_description: |
    Measure your energy consumption with the pulse LED on your smart meter -
    ESP32-S3
  
  # Define the GPIO pins
  pulse_pin: GPIO1
  pulse2_pin: GPIO3
  pulse3_pin: GPIO5
  pulse4_pin: GPIO7
  status_led: GPIO9

esphome:
  name: esphome_pulse
  # name_add_mac_suffix: false
  
esp32:
  # board: m5stack-stamps3
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

packages:
  # logger:     !include common/logger.yaml
  wifi:       !include common/wifi.yaml
  ota:        !include common/ota.yaml
  api:        !include common/api.yaml
  web_server: !include common/web_server.yaml
  status:     !include common/status.yaml

  pulse_meter:  !include components/pulse_meter.yaml

  remote_package:
    url: https://github.com/klaasnicolaas/home-assistant-glow/
    ref: "4.2.3"
    files:
      - components/basis.yaml
    #  - components/updates.yaml
    #  - components/status_led.yaml
    #  - components/pulse_meter.yaml

###################################################################################
light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO09
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    name: "Status Pulse"
    
